server:
  port: 8080

spring:
  application:
    name: multimart-platform

  datasource:
    # Cấu hình H2 Database in-memory để chạy test/dev ngay lập tức
    url: jdbc:h2:mem:multimart_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 

    # Khi có PostgreSQL, bạn chỉ cần thay đổi 4 dòng này:
    # url: jdbc:postgresql://localhost:5432/multimart_db
    # driver-class-name: org.postgresql.Driver
    # username: postgres
    # password: postgrespassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  # Khóa bí mật HMAC-SHA256 (tối thiểu 256 bits)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration-ms: 900000 # 15 phút
  refresh-token-expiration-ms: 604800000 # 7 ngày
