server:
  port: 8080

spring:
  application:
    name: multimart-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/multimart_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        auto-startup: ${RABBITMQ_AUTO_STARTUP:false}
        acknowledge-mode: auto
        concurrency: 2
        max-concurrency: 5
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          multiplier: 2

jwt:
  # Khóa bí mật HMAC-SHA256 (tối thiểu 256 bits)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration-ms: 900000 # 15 phút
  refresh-token-expiration-ms: 604800000 # 7 ngày
